import {describe,it,expect,vi} from 'vitest';
import {JSDOM} from 'jsdom';
import {inspectTranslation,translatePost,appendTranslations,validateTranslationTarget} from './tweet-translation.js';
function dom(body){const w=new JSDOM(body,{url:'https://x.com/alice/status/1?lang=zh-cn'}).window;vi.stubGlobal('document',w.document);vi.stubGlobal('location',w.location);return w;}
const shell=inner=>`<article data-testid="tweet"><a href="/alice/status/1"><time>now</time></a>${inner}</article>`;
describe('X visible translation contract',()=>{
 it('isolates target text and expands links without consuming quoted translation',()=>{const w=dom(shell('<button aria-label="显示原文"></button><div data-testid="tweetText" lang="zh">你好 <a href="https://example.com/full">exam…</a></div><div role="link"><div data-testid="tweetText" lang="en">quoted</div><button aria-label="显示翻译"></button></div>'));try{expect(inspectTranslation('1')).toMatchObject({state:'translated',text:'你好 https://example.com/full',lang:'zh',selector:null});expect(inspectTranslation('2').state).toBe('wrong_page');}finally{w.close();vi.unstubAllGlobals();}});
 it('returns observed button selector, marks truncation and fails on ambiguous ownership',()=>{const w=dom(shell('<button aria-label="显示翻译"></button><div data-testid="tweetText" lang="en">hello</div><button data-testid="tweet-text-show-more-link">More</button>'));try{expect(inspectTranslation('1')).toMatchObject({state:'available',selector:'button[aria-label="显示翻译"]',nth:0,truncated:true});w.document.body.innerHTML+=shell('<div data-testid="tweetText">other</div>');expect(inspectTranslation('1').state).toBe('missing_post');}finally{w.close();vi.unstubAllGlobals();}});
 it('clicks only observed control and preserves source data',async()=>{let clock=0;const page={goto:vi.fn(),evaluate:vi.fn().mockResolvedValueOnce({state:'available',lang:'en',selector:'button[aria-label="显示翻译"]',nth:0}).mockResolvedValue({state:'translated',lang:'zh',text:'你好',truncated:false}),click:vi.fn()};const post={id:'1',text:'hello',lang:'en'};const result=await translatePost(page,post,{deadline:1000,now:()=>clock,sleep:async ms=>{clock+=ms;}});expect(result).toMatchObject({status:'translated',text:'你好',source_lang:'en',completeness:'unknown'});expect(page.click).toHaveBeenCalledWith('button[aria-label="显示翻译"]',{nth:0});expect(post.text).toBe('hello');});
 it('does not label a non-Chinese translation as Chinese',async()=>{const page={goto:vi.fn(),evaluate:vi.fn().mockResolvedValue({state:'translated',lang:'fr',text:'bonjour'})};expect(await translatePost(page,{id:'1',text:'hello'},{deadline:Date.now()+1000})).toMatchObject({status:'unavailable',text:null,reason:'target_language_mismatch'});});
 it('reports absent controls and bounded wait without returning original as translation',async()=>{let clock=0;const page={goto:vi.fn(),evaluate:vi.fn().mockResolvedValue({state:'unavailable',lang:'en',text:'hello'}),click:vi.fn()};expect(await translatePost(page,{id:'1',text:'hello'},{deadline:1000,now:()=>clock,sleep:async ms=>{clock+=ms;}})).toMatchObject({status:'unavailable',text:null,reason:'translation_not_offered'});expect(page.click).not.toHaveBeenCalled();});
 it('keeps partial status when the translated webpage is visibly truncated',async()=>{const page={goto:vi.fn(),evaluate:vi.fn().mockResolvedValue({state:'translated',lang:'zh',text:'部分',truncated:true})};expect(await translatePost(page,{id:'1',text:'full'},{deadline:Date.now()+1000})).toMatchObject({status:'translated',completeness:'partial'});});
 it('propagates login expiry rather than calling it an unavailable translation',async()=>{const page={goto:vi.fn(),evaluate:vi.fn().mockResolvedValue({state:'login_required'})};await expect(translatePost(page,{id:'1',text:'hello'},{deadline:Date.now()+1000})).rejects.toThrow(/login/);});
 it('skips Chinese and rejects unsupported Article and exhausted budgets explicitly',async()=>{const page={goto:vi.fn()};expect((await translatePost(page,{id:'1',text:'你好',lang:'zh'})).status).toBe('not_needed');expect((await translatePost(page,{id:'1',text:'hello',article:{}})).reason).toBe('article_translation_not_supported');expect((await translatePost(page,{id:'1',text:'hello'},{deadline:0})).reason).toBe('translation_budget_exhausted');expect(page.goto).not.toHaveBeenCalled();});
 it('is opt-in, validates before browsing and annotates each related post',async()=>{expect(()=>validateTranslationTarget('fr')).toThrow();const result={root_id:'1',posts:{'1':{id:'1',text:'hello',article:{}},'2':{id:'2',text:'你好',lang:'zh'}},warnings:[]};await appendTranslations({},result,undefined);expect(result.posts['1'].translation).toBeUndefined();await appendTranslations({},result,'zh-CN');expect(result.posts['1'].translation.status).toBe('unavailable');expect(result.posts['2'].translation.status).toBe('not_needed');expect(result.warnings).toHaveLength(1);});
});
